### PR TITLE
build: added symfony 5/6 support

### PR DESCRIPTION
**Pull request by JefVerschuere**
- adds support for symfony5 applications

### CODE REVIEW

**Comment by paali** [comment]
This would be real nice :)

**Comment by emri99** [comment]
It will be merged in the next few days ;)

**Comment by paali** [comment]
Now that I think about this I think `symfony/finder:^6.0` would just work as well.

Today 5.x is more relevat for us still.

**Review by emri99 — APPROVED** [review]

**Comment by emri99** [comment]
@paali Sorry for the delay and thanks for the ping ;)

Added support to Symfony 6 as well. 
It hasn't been tested although this would be really surprising that it breaks something 🤞 

Version published : [0.3.0 ](https://github.com/Coffreo/js-translation-extractor/releases/tag/0.3.0)

**Pull request merged**
