### PR TITLE
PHP 8.0 support

### PR DESCRIPTION
**Pull request by paali**
Code seems to work with PHP8 already so just a minor composer.json change.

### CODE REVIEW

**Comment by emri99** [comment]
Thanks for your contribution. I'll take a look on the checks before merging and creating a tag

**Comment by emri99** [comment]
The travis-ci has drastically changed since last release, it's now a very cumbersome process for open source projects... I'm currently thinking of migrating to another CI service but that's not something I can do in the next few days.
I'm a little worried of merging this without tests. And I'm not able to perform those on my workstation currently.

Can you run unit tests on your side under PHP 8 and paste the results here ?

```
vendor/bin/simple-phpunit
```

Thanks ;)

**Comment by paali** [comment]
```
./vendor/bin/simple-phpunit 
PHPUnit 9.4.4 by Sebastian Bergmann and contributors.

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 14:
  - Element 'phpunit', attribute 'syntaxCheck': The attribute 'syntaxCheck' is not allowed.
  - Element 'phpunit', attribute 'codecoverage': The attribute 'codecoverage' is not allowed.

  Line 16:
  - Element 'formatter': This element is not expected.

  Test results may not be as expected.


Testing 
......                                                              6 / 6 (100%)

Time: 00:00.009, Memory: 6.00 MB

OK (6 tests, 88 assertions)
```

**Comment by emri99** [comment]
A new release will be created soon, just the time to ensure that there is no regression with older PHP versions ;) (I'm confident, but I want to be sure as we use this project on those versions)
Depending on the result, the new release will be tagged as 0.2.0 if it's still work properly on PHP5 / PHP7.X or as 1.0.0 if it's not the case.

**Comment by emri99** [comment]
Released version 0.2.0

**Pull request merged**
